//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vote.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante()
        {
            this.Votos = new HashSet<Voto>();
        }
    
        public int Id { get; set; }
        public int IdCategoria { get; set; }
        public int IdModalidade { get; set; }
        public Nullable<decimal> DistanciaMedia { get; set; }
        public string Endereco { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> ValorMedio { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Modalidade Modalidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voto> Votos { get; set; }
    }
}
