//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vote.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public int Id { get; set; }
        public int IdRestaurante { get; set; }
        public int IdFuncionario { get; set; }
        public System.DateTime DataVoto { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Restaurante Restaurante { get; set; }
    }
}
